### ISSUE TITLE
Downloads zip again even if already downloaded

### ISSUE THREAD

**Issue by brennantaylor** [guidomb/carthage_cache#17]
Into the exact same spot too.

```text
 ~/ios-project> bundle exec carthage_cache install
Downloading archive with key '/var/folders/hq/zjy00w7j6szb_bxbf5zz20r02zy7r0/T/carthage_cache/3774467b97c328c10589f2cd4991102dc7e9eed47d0086b53f6063a5f79d8880.zip'.
Unarchiving '/var/folders/hq/zjy00w7j6szb_bxbf5zz20r02zy7r0/T/carthage_cache/3774467b97c328c10589f2cd4991102dc7e9eed47d0086b53f6063a5f79d8880.zip' into './Carthage/Build'.
 ~/ios-project> bundle exec carthage_cache install
Downloading archive with key '/var/folders/hq/zjy00w7j6szb_bxbf5zz20r02zy7r0/T/carthage_cache/3774467b97c328c10589f2cd4991102dc7e9eed47d0086b53f6063a5f79d8880.zip'.
Unarchiving '/var/folders/hq/zjy00w7j6szb_bxbf5zz20r02zy7r0/T/carthage_cache/3774467b97c328c10589f2cd4991102dc7e9eed47d0086b53f6063a5f79d8880.zip' into './Carthage/Build'.
```

**Comment by guidomb** [comment]
Yeah this is a really nice to have. I've kind of busy this following month. I'll try to add this ASAP but if you want to submit a PR that is more than welcomed!

**Comment by brennantaylor** [comment]
Cool! I mostly wanted to get my insights written down as I go through the process of setting this up for the project I work on.

Ruby is not my forte and it may take some time for me to get up to speed on your tests but I will try to help. Thanks.

**Comment by mokagio** [comment]
I'd love to help with this, as it would greatly improve our build times since we wouldn't download hundreds of MB every build.

I think this could be implemented by:

- Having a standard temp folder, rather than using `Dir.tmpdir`
- Looking into the standard temp folder before attempting to download

I might be able to have time to draft out a PR for this within the week.

**Comment by mokagio** [comment]
As a second step we might want to have some way to cleanup that _internal cache_ folder. ;)

**Comment by guidomb** [comment]
That would be awesome!!! Maybe you can start from here https://github.com/guidomb/carthage_cache/pull/21.

**Comment by mokagio** [comment]
Hey @guidomb, yesterday I dove into coding and didn't notice #21 was there 😳 

I opened #24 instead.

**Comment by brennantaylor** [comment]
Thanks!
