### ISSUE TITLE
Will keep installing even if you are already up to date

### ISSUE THREAD

**Issue by brennantaylor** [guidomb/carthage_cache#18]
Currently in the project I work on we do some work to remember the `Cartfile.resolved` and xcode version (I like that `carthage_cache` uses the `swiftc` version). Just like in this blog post https://robots.thoughtbot.com/caching-carthage-con-circleci

This allows us to elide carthage from most developer's workflow for the most part. They just pull new code and when `Cartfile.resolved` changes or they update xcode then they may experience a bootstrap (this is about to be turbo charged by carthage_cache 😎 ).

I was wondering if it makes sense for `carthage_cache` to support the use case: "Is the state of my current artifacts in a good state compared to my `Cartfile.resolved` and `swiftc` version".

Probably by tracking the hash from the last zip that was dumped into `Carthage/Build`.

**Comment by guidomb** [comment]
Sorry for the super super delayed response. This issue flew under my radar. This is a feature that I've been thinking it would be nice for quite a while. In think having some sort of check that triggers on every git branch change, pull, merge or rebase would be nice. This check will tell if you if you need to run `carthage_cache install` or depending on your config it could do it automatically. I think that with the latest local cache #24, having this feature would improve the UX a lot. 

Do you feel like sending a PR?

**Comment by brennantaylor** [comment]
We basically already do that we just check every build since it is just doing a `cmp` between 2 files.

```shell
# This file is called bootstrap-carthage-if-needed

#!/bin/sh -eux

mkdir -p Carthage
BOOTSTRAPED_VERSION=Carthage/carthage-sdk-version
CURRENT_VERSION=Carthage/carthage-sdk-version-current
xcodebuild -version > $CURRENT_VERSION

if ! cmp -s Cartfile.resolved Carthage/Cartfile.resolved || ! cmp -s $BOOTSTRAPED_VERSION $CURRENT_VERSION; then
  ./bin/bootstrap-carthage
fi
```

**Comment by brennantaylor** [comment]
I'll see what I can do. This gets much more complicated with swift 2.3 and swift 3.0 as it is no longer as easy to figure out which compiler is being used.

**Comment by guidomb** [comment]
I was thinking about this and I maybe a good option would be to have a `carthage_cache.lock` file that contains the digest of the last installed archive (this file should not be under version control). Then `carthage_cache` can check the if the current's digest is the same as the one in the lock file, if not a you need to run `carthage_cache install`.

**Comment by guidomb** [comment]
I have implemented a `validate` command that compares the current digest against the one stored (by the `publish` command) inside the `CarthageCache.lock` file.

https://github.com/guidomb/carthage_cache/blob/master/exe/carthage_cache#L100
