### ISSUE TITLE
Policy Creation Error: Statement IDs (SID) must be alpha-numeric

### ISSUE THREAD

**Issue by Dschee** [guidomb/carthage_cache#22]
Following the README I configured this new policy on AWS:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "autogenerated-id",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::carthage-cache"
            ]
        },
        {
            "Sid": "autogenerated-id",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::carthage-cache/*"
            ]
        }
    ]
}
```

When trying to save it I got the following error message:

> An error occurred: Statement IDs (SID) must be alpha-numeric. Check that your input satisfies the regular expression [0-9A-Za-z]*

I had to change the `autogenerated-id` entries to `autogeneratedId` for it to save. I hope this doesn't stop carthage-cache from working. If it is I will notify you after trying it – in any case the README should be updated.

**Comment by Dschee** [comment]
Okay this didn't work either, I am now additionally getting this error:

> This policy contains the following error: The Statement Ids in the policy are not unique For more information about the IAM policy grammar, see AWS IAM Policies.

**Comment by Dschee** [comment]
Okay, I setup the policy with the generator, it looks the same only that the Sids are different. Maybe we should note in the README that the Sid needs to be something unique...?

**Comment by guidomb** [comment]
@Dschee Thanks for the suggestion I will clarify that in the docs.
