### ISSUE TITLE
Branch on carthage_cache exist

### ISSUE THREAD

**Issue by AndrewSB** [guidomb/carthage_cache#26]
It would be really awesome to be able to branch on `carthage_cache exist`, much like how you can do 

```bash
carthage_cache install || fallback
```

Since I'm going to be running this on CI, I don't want to have to re-install if my Carthage directory is cached

**Comment by guidomb** [comment]
If I understand correctly you want to avoid downloading the archive for every build if there a local cache already, am I correct? If that is the case, in the latest release we added support for local cache. Meaning the that `carthage_cache` won't download an archive if a local copy exists.

Will that work for you?

**Comment by AndrewSB** [comment]
oh wow, yeah. That would

So if I understand correctly, if I run `carthage_cache install` and I already have everything correctly installed in `Carthage/Build`, it won't re-download the archive?

**Comment by guidomb** [comment]
Yeah that is correct you can check that [here](https://github.com/guidomb/carthage_cache/blob/master/lib/carthage_cache/archive_installer.rb#L35)

I understand that this would work for you so I am closing this issue. Feel free to open a new one if you found a problem or have another question.
