### ISSUE TITLE
Can't unzip cache?

### ISSUE THREAD

**Issue by AndrewSB** [guidomb/carthage_cache#28]
Getting is error on all the caches I publish

```
Downloading archive with key '/Users/asb/Library/Caches/carthage_cache/17247b81d5aa77a25c637c25f3cdddbc3c9c98d02a8081ff9e9927053f3d1f69.zip'.
Unarchiving '/Users/asb/Library/Caches/carthage_cache/17247b81d5aa77a25c637c25f3cdddbc3c9c98d02a8081ff9e9927053f3d1f69.zip' into './Carthage/Build'.
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/asb/Library/Caches/carthage_cache/17247b81d5aa77a25c637c25f3cdddbc3c9c98d02a8081ff9e9927053f3d1f69.zip or
        /Users/asb/Library/Caches/carthage_cache/17247b81d5aa77a25c637c25f3cdddbc3c9c98d02a8081ff9e9927053f3d1f69.zip.zip, and cannot find /Users/asb/Library/Caches/carthage_cache/17247b81d5aa77a25c637c25f3cdddbc3c9c98d02a8081ff9e9927053f3d1f69.zip.ZIP, period.
```

**Comment by guidomb** [comment]
That is weird. I am using the zip command to archive and unarchive. If you try to open zip archive with macOS you get the same error?

**Comment by AndrewSB** [comment]
Yeah
<img width="394" alt="screen shot 2016-11-18 at 3 16 50 pm" src="https://cloud.githubusercontent.com/assets/3814772/20450030/0db10b76-ada2-11e6-9809-e97bbe5c2620.png">

super weird

**Comment by guidomb** [comment]
@AndrewSB Are you still this issue? Because I am not able to reproduce it. The archiver class is really simple. It only calls the `zip` command, check it out [here](https://github.com/guidomb/carthage_cache/blob/master/lib/carthage_cache/archiver.rb#L13).

Can you try executing that command yourself and see what happens?

**Comment by guidomb** [comment]
I haven't heard anything on this issue nor I was able to reproduce it. I am closing it. Feel free to re open it if you have any news on it. Thanks!

**Comment by AndrewSB** [comment]
Sorry for going AWOL @guidomb! I haven't seen the issue for a while. I feel as if it was a problem with the machine I was running the command on, and not carthage_cache.

I'll definitely report back here if I see it again 😄
