### ISSUE TITLE
error: . Use --trace to view backtrace

### ISSUE THREAD

**Issue by freesuraj** [guidomb/carthage_cache#29]
Keep getting this error

**Comment by guidomb** [comment]
Thanks for submitting an issue! Most probably there is something wrong with carthage cache's configuration. Could you tell me how are you executing carthage_cache? Also you can add the `--trace` flag to show the full stack trace, please add that and share me stack trace.

**Comment by alphatroya** [comment]
I met this problem when define wrong region parameter in .carthage_cache.yml

**Comment by guidomb** [comment]
Yeah error reporting is something that needs to be improved. If you like contributing that cold be a good starting point. Let me know if you need any help with that. 

I understand that you were able to run carthage_cache successfully so I am closing this issue. If you encounter any other problem feel free to open a new open a new issue.
