### ISSUE TITLE
Remove unused binaries from cache archive.

### ISSUE THREAD

**Issue by guidomb** [guidomb/carthage_cache#3]
We need to resolve [this](https://github.com/guidomb/carthage_cache/blob/6b34ba6aa5ad2251491316e87b699c9b365a788f/lib/carthage_cache/archive_builder.rb#L28) TODO

**Comment by guidomb** [comment]
This was already implemented with `prune` command or `-p` option in the `publish` command.

**Comment by Dschee** [comment]
Doesn't removing the .dsym and .bcsymbolfilemap files stop us from receiving detailed information about any crashes and prevent us from publishin the app both locally or on the CI?

I mean, I'm all in for deleting all binaries that are not needed like frameworks not any more referenced in the Cartfile. So I want to cleanup "unused binaries" as this issue is titled. But the dsym and bcsymbolmap files aren't unused, are they?

I would love to only prune really unused binaries ...

**Comment by guidomb** [comment]
@Dschee To be honest I was hesitant of this change too but as far as I know when you download pre compiled frameworks with carthage (when you DONT use `--no-use-binaries` option`) you don't get his files either so I assumed there where not necessary. Not 100% sure until I deploy my app to production, find a crash and see that Crashlytics is not working but I'm think this shouldn't affect that.

**Comment by Dschee** [comment]
@guidomb As you can see starting at [this line](https://github.com/Carthage/Carthage/blob/master/Source/carthage/Archive.swift#L90) when you build your precompiled frameworks for providing for download as a framework creator using `carthage archive --no-skip-current` as [documented in the README](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file), they added code specifically to add `.dsym` files and `.bcsymbolmap` files. So, my guess is that they are needed – also I'm pretty sure to remember Crashlytics needing those .dsym files when I first used it back a few years ago.

**Comment by guidomb** [comment]
@Dschee Ooops! I guess you are correct. I'll revert deleting the `.dSYM` file but I need to find a way to map the `.bcsymbolmap` files to their corresponding `.framework` file. I guess I'll have to dive into Carthage's source code. They seem to have figured that out.

👍

**Comment by guidomb** [comment]
Well based on Carthage source code the following will do the trick

```
/usr/bin/xcrun dwarfdump --uuid Carthage/Build/iOS/ReactiveObjC.framework.dSYM
```

**Comment by guidomb** [comment]
[This](https://github.com/guidomb/carthage_cache/commit/6bc0b77f1cb45403196283dea3e8761b71c6aef9) commit makes `prune` command to only delete `.dSYM` and `.bcsymbolmap` files for frameworks that are no longer being used. Once CI build passes I'll make a new release, version `0.8.1`.

**Comment by Dschee** [comment]
Thanks for the quick update! 👍

**Comment by guidomb** [comment]
Release [0.8.3](https://github.com/guidomb/carthage_cache/releases/tag/v0.8.3) found a couple of bugs while testing it with some projects but that one should be working fine. Let me know if you found any issues @Dschee

**Comment by Dschee** [comment]
@guidomb Yeah I just tried v0.8.3 and I've come across an issue: I had completely deleted my Carthage folder and had run `carthage update --platform ios,tvos --no-use-binaries` which produced some frameworks successfully. But once I did a `carthage_cache publish` with `prune_on_publish` set to `true` in my `.carthage_cache.yml` two of my frameworks were deleted.

Here's my Cartfile and Cartfile.private content:

```
# AlertView Helper
github "sberrevoets/SDCAlertView" ~> 7.1
github "robb/RBBAnimation" ~> 0.4
github "sberrevoets/SDCAutoLayout" ~> 2.0

# Progress HUD view
github "Dschee/SVProgressHUD" "283c43b0f27b92ef6c746b7323cbd3ee6270b81c"

# Replacement for Apple's Reachability re-written in Swift with closures
github "ashleymills/Reachability.swift" ~> 3.0

# Handy Swift features that didn't make it into the Swift standard library.
github "Flinesoft/HandySwift" ~> 1.4

# The better way to deal with JSON data in Swift
github "SwiftyJSON/SwiftyJSON" ~> 3.1

# Delightful on-disk cache (written in Swift)
github "aschuch/AwesomeCache" ~> 5.0

# Fabulous Image Processing in Swift
github "gavinbunney/Toucan" ~> 0.6

# Display resolution independent SVGs in iOS.
github "Dschee/JAMSVGImage" "bundle-framework-carthage-tvos-cacheopt"

# The Swift (and Objective-C) testing framework.
github "Quick/Quick"

# A Matcher Framework for Swift and Objective-C
github "Quick/Nimble"

# Snapshot view unit tests for iOS
github "facebook/ios-snapshot-test-case"

```

The two frameworks that were deleted are namely Reachability and ios-snapshot-test-case (which produces a framework called FBSnapshotTestCase). I've now turned off the `prune_on_publish` option and it works fine again – so you may want to fix this. I hope this helps!

**Comment by guidomb** [comment]
I am on the road now but it seems that your problem is related with framework name being different from how it appears in the Cartfile.resolved. Check out the README and look for white list file. You need to tell carthage cache how an entry in the Cartfile.resolved maps to the a .framework file. 

| Guido Marucci Blas |

**Comment by guidomb** [comment]
Check the last usage [example](https://github.com/guidomb/carthage_cache#usage). It seems that you need to whitelist this libs. Create a `carthage_cache_white_list.yml` file

```yaml
"FBSnapshotTestCase": "ios-snapshot-test-case"
"Reachability": "Reachability.swift"
```

the you can execute publish with this white list file like `carthage_cache publish -p -w carthage_cache_white_list.yml`

or you can add it to your `.carthage_cache.yml` like

```yml
:prune_on_publish: true
:prune_white_list: .carthage_cache_prune_white_list.yml
```

Let me know if that fixed your issue.

**Comment by Dschee** [comment]
Thanks @guidomb for the explanation.

But adding a whitelist and keeping it up-to-date adds too much effort into this especially given there are multiple people on the team. Before I had this issue I could tell them "just use `carthage_cache install || carthage update` instead `carthage update` and `carthage update && carthage_cache publish` instead of `carthage update`" as they didn't have to change the `carthage_cache.yml` or any other file. But with the whitelist it becomes completely impractical to add another layer of information everybody has to know about. So, we're now back to deleting unused binaries by hand (me) or not at all (the others). At least no framework is missing now (even if uploads are slower for the others).

By the way, when trying the whitelist approach I couldn't find any indication on how to solve cases where a single entry in the Cartfile produces multiple differently named frameworks that are all needed (like when integrating the Facebook SDK).

**Comment by guidomb** [comment]
Yeah I am sorry to hear that and to be honest I feel the same. The problem is that the situation is quite complex per se and my solution was quick hack that I've made to get things working and move on. But I do agree with you. The current solution is far from ideal. I would like for carthage_cache to automatically do that mapping. I guess that playing around a little but xcodebuild to inspect the dependencies project's target this process could be automated. But I haven't got the time to do so.

It would be a nice addition if you feel like tackling this problem.
