### ISSUE TITLE
`warning: Insecure world writable dir /usr/local in PATH, mode 040777` after installing carthage_cache

### ISSUE THREAD

**Issue by bensarz** [guidomb/carthage_cache#30]
Here's the full warning, every time I run carthage_cache command:

```zsh
$ carthage_cache install
/Users/[redacted]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/carthage_cache-0.5.0/lib/carthage_cache/shell_command_executor.rb:6: warning: Insecure world writable dir /usr/local in PATH, mode 040777
```

**Comment by guidomb** [comment]
Seems to be a problem with your ruby setup. 

 - https://stackoverflow.com/questions/5380671/getting-the-warning-insecure-world-writable-dir-home-chance-in-path-mode-04
 - https://stackoverflow.com/questions/26711249/how-to-solve-insecure-world-writable-dir-usr-in-path-mode-040777-warning-on-rub
 - https://stackoverflow.com/questions/29016525/how-to-fix-insecure-world-error
