### ISSUE TITLE
Exit code for carthage_cache exist

### ISSUE THREAD

**Issue by ganjarpanji** [guidomb/carthage_cache#39]
currently `carthage_cache install || carthage bootstrap` is a command that we used, whenever there is no cache, it will run bootstrap.
but in some situations we only need cache status to do some scenarios in dependency build script.
so, it will be better if carthage_cache could return some exist status and we could utilize it, for example : 
`1` =  if there is no cache exist
`0` = if cache is exist.

**Comment by guidomb** [comment]
You can do `carthage_cache exist -s` which will output `true` or `false`

https://github.com/guidomb/carthage_cache/blob/master/exe/carthage_cache#L29
