### ISSUE TITLE
Is it possible to cache multiple projects in the same Bucket?

### ISSUE THREAD

**Issue by samuelbeek** [guidomb/carthage_cache#42]
We want to use `carthage_cache` across all our projects. Is it possible to use the same bucket for all of them or should we use one bucket per project?

Cheers, 
Sam

**Comment by guidomb** [comment]
Hi Sam, yes it is possible and recommended to do so. Carthage cache uses a digest of the `Cartfile.resovled` + version of the compiler to define the cache key. If your projects share the same compiler and `Cartfile.resolved` files cache will be reused between projects.

Just take into account that Carthage cache does not cache at the dependency level so if `Cartfile.resolved` files don't match you won't be able to share caches between projects. More on this in https://github.com/guidomb/carthage_cache/issues/35 and  https://github.com/guidomb/carthage_cache/issues/12

**Comment by samuelbeek** [comment]
Thanks, super clear 👍
