### ISSUE TITLE
[Question] Store carthage cache inside bucket's folder

### ISSUE THREAD

**Issue by serluca** [guidomb/carthage_cache#44]
I couldn't find the answer looking through the documentation and previous issues, I was wondering if is possible to store the carthage cache inside a bucket's folder

**Comment by guidomb** [comment]
I'm 99% sure that is not possible to do that. Carthage Cache uses AWS gem to access S3 and the APIs available to interact with S3 separates the bucket name from the object key.

You can read the code that access S3 (here](https://github.com/guidomb/carthage_cache/blob/master/lib/carthage_cache/repository.rb#L5)

**Comment by serluca** [comment]
Hi @guidomb thanks for getting back to me, I found a solution for the issue, I'm preparing a PR

**Comment by serluca** [comment]
Hi @guidomb I think you can close this one now :)
