### ISSUE TITLE
How to pass replace All to command

### ISSUE THREAD

**Issue by Autoc0diq** [guidomb/carthage_cache#7]
When running a script on a CI machine, there's no way to tell carthage_cache to automatically overwrite the current Carthage/Build folder if things are already there.

**Comment by guidomb** [comment]
Yes you are right. I was thinking of adding this feature. If you want to submit a PR I would appreciate it but I would try to add this on the weekend. I wasn't experience this issue in my CI because I use travis and I get a fresh VM every time I run a build.
